### ISSUE TITLE
نحوه کار با بات

### ISSUE THREAD

**Issue by shahriaarrr** [Mehranalam/Secure-telegrambot#3]
همانطور که در توضیحات نوشته شده این یک سلف باته و روی اکانت سوار میشه.بنابراین خیلی بهتره که نحوه پیاده سازی و فعالسازی این ربات بر روی اکانت در توضیحات این پروژه درج شود.

**Comment by Mehranalam** [comment]
بلی بلی شهریار عزیز حتما به صورت یک ویکی ایجاد میشود ممنونم از توجهت❤❤

**Comment by Mehranalam** [comment]
حل شد https://github.com/Mehranalam/Secure-telegrambot/wiki/%DA%86%DA%AF%D9%88%D9%86%D9%87-%D8%A7%D8%B2-%D8%A7%DB%8C%D9%86-%D9%BE%D8%B1%D9%88%DA%98%D9%87-%D8%A7%D8%B3%D8%AA%D9%81%D8%A7%D8%AF%D9%87-%DA%A9%D8%A7%D9%81%DB%8C-%D8%B1%D8%A7-%D8%A8%D8%A8%D8%B1%DB%8C%D9%85%D8%9F

**Comment by shahriaarrr** [comment]
ایول✌❤💣
